name: dart_browser_loader
description: A starting point for Dart libraries or applications.
version: 0.0.4
homepage: https://github.com/leftyio/dart_browser_loader
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  browser: ^0.10.0+2

dev_dependencies:
  test: ^0.12.0
