name: dart_browser_loader
description: A starting point for Dart libraries or applications.
version: 0.0.7-nullsafety.0
homepage: https://github.com/leftyio/dart_browser_loader

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  pedantic: ^1.10.0-nullsafety

dev_dependencies:
  test: ^1.16.0-nullsafety
  build_runner: ^1.10.6
  build_web_compilers: ^2.15.2
