name: dart_browser_loader
description: A starting point for Dart libraries or applications.
version: 0.0.5
homepage: https://github.com/leftyio/dart_browser_loader
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dev_dependencies:
  test: ^1.3.0
